### ISSUE TITLE
auth.json not found

### ISSUE THREAD

**Issue by ITFactoryAUT** [Nono31/InstaBot#2]
Hello,
after compiling and starting the app I get an exception that the auth.json file is not found!

Can you please explain how to configure the app?

greetings

**Comment by Nono31** [comment]
Hello,
When you start the application for first time, you get a message like "Please configure auth.json"
Go in config folder where the exe is, and open auth.json and put you login and password only.
You can also customize bot.json to put your tag and stop tags, The others are the max amount of like allowed by instagram per day so, you can put less but no more.

You are free to update the readme if you want with a pull request
Tell me if you have trouble after that.

**Comment by biapar** [comment]
The file auth.json and bot.json are not into the solution.
