### ISSUE TITLE
EnqueueMedia Error

### ISSUE THREAD

**Issue by biapar** [Nono31/InstaBot#3]
Error:

Eccezione non gestita: System.Exception: Fatal error occured in sub task ---> System.AggregateException: Una o più eccezioni di attività non sono state osservate da Waiting nell'attività oppure hanno acceduto alla relativa proprietà Exception. Di conseguenza, l'eccezione non osservata è stata rigenerata dal thread di finalizzazione. ---> System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in InstaBot.Console.Tasks.FollowingTask.<>c__DisplayClass33_0.<EnqueueMedia>b__0(Media x) in C:\Tmp\InstaBot-master\Src\InstaBot.Console\Tasks\FollowingTask.cs:riga 180
   in System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   in InstaBot.Console.Tasks.FollowingTask.<EnqueueMedia>d__33.MoveNext() in C:\Tmp\InstaBot-master\Src\InstaBot.Console\Tasks\FollowingTask.cs:riga 178
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   in InstaBot.Console.Tasks.FollowingTask.<Follow>d__32.MoveNext() in C:\Tmp\InstaBot-master\Src\InstaBot.Console\Tasks\FollowingTask.cs:riga 83
   --- Fine della traccia dello stack dell'eccezione interna ---
   --- Fine della traccia dello stack dell'eccezione interna ---
   in InstaBot.Console.InstaBot.TaskScheduler_UnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs e) in C:\Tmp\InstaBot-master\Src\InstaBot.Console\InstaBot.cs:riga 45
   in System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)
   in System.Threading.Tasks.TaskExceptionHolder.Finalize()

**Comment by biapar** [comment]
?

**Comment by Nono31** [comment]
It look like your bot settings are null, can you ensure the json files settings are ok ?
